theme:        jekyll-theme-slate

plugins:
  - jekyll-sitemap

title:        IGME 110
description:  Introduction to Interactive Media


discordInvite:  "https://discord.gg/jCyt3RG"
classStartTime: "6:30pm"
